import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub, AiFillLinkedin, AiFillFacebook, AiOutlineFolder} from 'react-icons/ai'
import Image from "next/image" // Allows us to customise and optimise images
import springLogo from "../../public/spring-logo.png"
import postgresqlLogo from "../../public/postgresql-logo.png"
import jsLogo from "../../public/js-icon.png"
import reactIcon from "../../public/react-icon.png"
import tailwindIcon from "../../public/tailwind-logo.png"
import InnerCursor from './api/innerCursor'
import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import svgavatar from '../../public/Svgavatar.svg'
import blackBackground from '../../public/blackBackground.jpeg'

//const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [mousePosition, setMousePosition] = useState({
    x: 0,
    y: 0
  })
  //console.log(mousePosition)

  const [cursorVariant, setCursorVariant] = useState("default");
  const [cursorVariantOuter, setCursorVariantOuter] = useState("outer");

  useEffect(() => {
    const mouseMove = (e) => {
      //console.log(e)
      setMousePosition({
        x: e.clientX - 5,
        y: e.clientY  - 5
      })
    }

    window.addEventListener("mousemove", mouseMove)

    return () => {
      window.removeEventListener("mousemove", mouseMove)
    }
  }, [])

  const variants = {
    default: {
      x: mousePosition.x,
      y: mousePosition.y,
      height: "10px",
      width: "10px"
    },
    outer: {
      x: mousePosition.x - 15,
      y: mousePosition.y - 15
    },
    text: {
      height: "30px",
      width: "30px",
      x: mousePosition.x - 10,
      y: mousePosition.y - 10
    },
    textOuter: {
      height: "20px",
      width: "20px",
      x: mousePosition.x - 5,
      y: mousePosition.y - 5
    },
  }

  const textEnter = () => setCursorVariant("text")
  const textLeave = () => setCursorVariant("default");
  const linkClick = () => {
    setCursorVariantOuter("textOuter");
  }
  const linkLeave = () => {
    setCursorVariantOuter("outer");
  }

  return (
    <div onMouseDown={linkClick} onMouseUp={linkLeave}>
      <Head>
        <title>Bav's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div 
            className='inner-cursor'
            variants={variants}
            animate={cursorVariant}
          />
      <motion.div 
            className='outer-cursor'
            variants={variants}
            animate={cursorVariantOuter}
          />
      
      <main className='bg-white px-10 text-black flex-col' >
        <section className= "h-screen max-h-[800px] w-4/5 min-w-[400px] mx-auto my-auto flex flex-col justify-items-center">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 onMouseEnter={textEnter} onMouseLeave={textLeave} className="bg-gradient-to-r from-blue-500 via-cyan-600 to-teal-500 bg-clip-text text-xl font-bold tracking-tighter hover:tracking-normal hover:text-transparent transition-all duration-300">Bav Nagarajah</h1>
            <ul onMouseEnter={textEnter} onMouseLeave={textLeave} className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl hover:text-cyan-500 transition-all hover:scale-110 '/></li>
              <li className='hover:scale-110 transition-all duration-300'><a href="#" className=' animate-text-moving-background bg-gradient-to-r from-blue-500 via-cyan-600 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          {/* <div className='relative mx-auto bg-gradient-to-tr from-pink-400 via-cyan-600 to-orange-400 animate-text-moving-background rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} fill objectFit="cover"/>
          </div> */}
          <div className='text-center p-10 pt-0 mx-auto '>
            
            <h2 className="animate-text-moving-background text-6xl py-2 font-extrabold tracking-tighter transition-all ease-in-out duration-500 bg-gradient-to-r from-blue-500 via-cyan-600 to-teal-500 bg-clip-text"><span onMouseEnter={textEnter} onMouseLeave={textLeave} className='animate-text hover:tracking-wide transition-all duration-300'>Bav</span> <span onMouseEnter={textEnter} onMouseLeave={textLeave} className='animate-text-gradient hover:tracking-wide transition-all duration-300'>Nagarajah</span></h2>
            <h3 className='text-xl py-2 uppercase tracking-widest bg-gradient-to-r from-blue-500 via-cyan-600 to-teal-500 bg-clip-text'>Software Engineer</h3>
            <p className='text-md py-5 text-gray-800 leading-8 duration-150'>
              Full-stack developer based in London, UK.  
            </p>
            <div className='relative mx-auto w- w-72 h-72 bg-gradient-to-b from-teal-500/30 to-blue-500/50 rounded-full overflow-hidden'>
              < Image src={svgavatar} layout="fill" objectFit="cover" className='hover:scale-110 transition-all duration-300 shadow-inner'/>
            </div>
            <div className='text-3xl flex justify-center gap-4 py-3 text-gray-600'>
            <a href="https://github.com/bav-07/" target="_blank" className="hover:scale-150 transition-all duration-300" onMouseEnter={textEnter} onMouseLeave={textLeave} onMouseDown={linkClick} onMouseOut={linkLeave}><AiFillGithub /></a>
            <a href="https://www.linkedin.com/in/bavaharsan-nagarajah-7418a2196/" target="_blank" className="hover:scale-150 transition-all duration-300" onMouseEnter={textEnter} onMouseLeave={textLeave} onMouseDown={linkClick} onMouseOut={linkLeave}><AiFillLinkedin /></a>
          </div>
          </div>
          
        </section>
        <section>
          <div className='mx-auto w-[60vw] min-w-[400px]'>
            <h3 className='text-3xl py-2 leading-8 text-gray-800 font-bold font-["Open Sans"]'>About</h3>
            <div className='leading-7'>
              <p>I graduated from <span className='text-cyan-600 font-bold' onMouseEnter={textEnter} onMouseLeave={textLeave}>Imperial College London</span> in 2022 with a Master's in Mechanical Engineering (MEng), 
              before transitioning into software development via the <span onMouseEnter={textEnter} onMouseLeave={textLeave} className='text-cyan-600 font-bold'>Bright Network Technology Academy</span>.
              </p>
              <p className='mt-5'>
                I'm experienced with front-end and back-end development. I'm currently developing my skills in a variety of 
                technologies.
              </p>
              <h4 className='py-2 mt-2 text-2xl font-bold'>Tech Stack</h4>
              <div className='flex'>
                <div className='flex flex-col gap-4 mx-auto items-center shadow-lg p-10 rounded-xl my-10 w-[40%]'>
                  <h4 className='-mb-2 font-bold'>Back-end</h4>
                  <Image src={"https://nerdysoft.com/wp-content/uploads/2021/11/java-14-1.svg"} width={50} height={50} style={{objectFit: "cover"}}/> 
                  <Image src={springLogo} height={50} style={{objectFit: "cover"}}/> 
                  <Image src={postgresqlLogo} height={50} style={{objectFit: "cover"}}/> 
                </div>
                <div className='flex flex-col gap-4 mx-auto items-center shadow-lg p-10 rounded-xl my-10 w-[40%]'>
                  <h4 className='-mb-2 font-bold'>Front-end</h4>
                  <Image src={reactIcon} height={50} style={{objectFit: "cover"}}/> 
                  <Image src={jsLogo} height={50} style={{objectFit: "cover"}}/> 
                  <Image src={tailwindIcon} height={50} style={{objectFit: "cover"}}/> 
                </div>
              </div>
              </div>
          </div>
        </section>
        <section>
          <h3 className='py-2 mt-2 text-2xl font-bold'>Portfolio</h3>
        </section>
      </main>
    </div>
  )
}
